version: "3.9"
services:
#  Image do Database Postgres imagelite-db
   db:
     image: postgres
     restart: always
     environment:
      - POSTGRES_DB=imagelite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     ports:
      - 5437:5432
     volumes:
      - ./data:/var/lib/postgresql/data
     networks:
      - postgres-network     
      
   pg-admin:
     image: dpage/pgadmin4
     restart: always
     environment:
        PGADMIN_DEFAULT_EMAIL: "marcelino.feliciano@outlook.com"
        PGADMIN_DEFAULT_PASSWORD: "pgAdmin2024"
     ports:
       - "15432:80"
     depends_on: 
       - db
     networks:
      - postgres-network
      
networks:
  postgres-network:
    driver: bridge
    